image: node

cache: # Cache modules in between jobs
  key: $CI_COMMIT_REF_SLUG
  paths:
    - Client/node_modules

before_script:
  - npm ci
  - cd Client
  - npm ci

stages:
  - setup # List of stages for jobs, and their order of execution
  - build
  - test
  - lint
  - prettier

node-setup:
  stage: setup
  script:
    - npm install -g typescript
    - npm install

build: # This job runs in the build stage, which runs first.
  stage: build
  script:
    - npm run build

test: # This job runs in the test stage.
  stage: test # It only starts when the job in the build stage completes successfully.
  script:
    - npm run test

lint:
  stage: lint
  script:
    - npm run lint

prettier:
  stage: prettier
  script:
    - npm run prettier-check
