image: node

cache: # Cache modules in between jobs
  key: $CI_COMMIT_REF_SLUG
  paths:
    - Client/node_modules

before_script:
  - npm ci
  - cd Client
  - npm ci

stages:
  - setup # List of stages for jobs, and their order of execution
  - build
  - component_test
  - e2e_test
  - lint
  - prettier

node-setup:
  stage: setup
  script:
    - npm install -g typescript
    - npm install

build: # This job runs in the build stage, which runs first.
  stage: build
  script:
    - npm run build

component_test: # This job runs in the test stage.
  stage: component_test # It only starts when the job in the build stage completes successfully.
  script:
    - npm run test

e2e_test:
  stage: e2e_test
  image: mcr.microsoft.com/playwright:v1.39.0-jammy
  script:
    - npx playwright install
    - npm run e2e

lint:
  stage: lint
  script:
    - npm run lint

prettier:
  stage: prettier
  script:
    - npm run prettier-write
    - npm run prettier-check
